# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClicksecretCli < Formula
  desc "clicksecret-cli"
  homepage "https://github.com/sikalabs/clicksecret-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/clicksecret-cli/releases/download/v0.1.0/clicksecret-cli_v0.1.0_darwin_arm64.tar.gz"
      sha256 "81ee4f8bd6da49b2485973ade44305f52692fd175e84fa54575aad818ea17c0e"

      def install
        bin.install "clicksecret-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/clicksecret-cli/releases/download/v0.1.0/clicksecret-cli_v0.1.0_darwin_amd64.tar.gz"
      sha256 "72744d9618b1997615776374c3ab7babdec55f7352ba8d6b0266333852e904cf"

      def install
        bin.install "clicksecret-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/clicksecret-cli/releases/download/v0.1.0/clicksecret-cli_v0.1.0_linux_arm64.tar.gz"
      sha256 "348802e9455767335c5e2a57b213b09a13369ae6cc133d34268eb819df5a26b2"

      def install
        bin.install "clicksecret-cli"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/clicksecret-cli/releases/download/v0.1.0/clicksecret-cli_v0.1.0_linux_amd64.tar.gz"
      sha256 "3079b9fa121dbdbc7bc4abe0cb53801fba154bea7866a6334cb4828d061fb8c5"

      def install
        bin.install "clicksecret-cli"
      end
    end
  end

  conflicts_with "clicksecret-cli-edge"

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/clicksecret-cli
    EOS
  end

  test do
    system "#{bin}/clicksecret-cli version"
  end
end
