# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class ClicksecretServer < Formula
  desc "clicksecret-server"
  homepage "https://github.com/sikalabs/clicksecret-server"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/clicksecret-server/releases/download/v0.1.0/clicksecret-server_v0.1.0_darwin_arm64.tar.gz"
      sha256 "96f823759b65446132b89331e8519d74f835d817677dce4d4e52ae0980dc8001"

      def install
        bin.install "clicksecret-server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/clicksecret-server/releases/download/v0.1.0/clicksecret-server_v0.1.0_darwin_amd64.tar.gz"
      sha256 "9e66f5ce6595f4f5621ef553edb2f126f99863d94a83d403867fb5cfc9f3d03d"

      def install
        bin.install "clicksecret-server"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/clicksecret-server/releases/download/v0.1.0/clicksecret-server_v0.1.0_linux_arm64.tar.gz"
      sha256 "59e5958ed849fa940d0e70479694bc46fb5fa2c9acc0d0c71bf0451ac24cf0f9"

      def install
        bin.install "clicksecret-server"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/clicksecret-server/releases/download/v0.1.0/clicksecret-server_v0.1.0_linux_amd64.tar.gz"
      sha256 "62c244eb99ada47c94bfd3096dd7cddc9d6faa0dfa41c53efb23762482abb629"

      def install
        bin.install "clicksecret-server"
      end
    end
  end

  conflicts_with "clicksecret-server-edge"

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/clicksecret-server
    EOS
  end

  test do
    system "#{bin}/clicksecret-server version"
  end
end
