# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dogsay < Formula
  desc "dogsay"
  homepage "https://github.com/sikalabs/dogsay"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/dogsay/releases/download/v0.1.0/dogsay_v0.1.0_darwin_amd64.tar.gz"
      sha256 "a004dfb9a9e483d471d5e8434c41001546e3a3e8d73dfd4cbcb15dffe3cb6f6f"

      def install
        bin.install "dogsay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/dogsay/releases/download/v0.1.0/dogsay_v0.1.0_darwin_arm64.tar.gz"
      sha256 "979694f369e3c7092981bcd0c2b7384878f4ec8c7bf672249813b28f64e35b52"

      def install
        bin.install "dogsay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/dogsay/releases/download/v0.1.0/dogsay_v0.1.0_linux_amd64.tar.gz"
      sha256 "d9ffd5b4bf36e07e859ddd04c6e70db19a2a5344cda13216a54d2012bfcdfde3"
      def install
        bin.install "dogsay"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/dogsay/releases/download/v0.1.0/dogsay_v0.1.0_linux_arm64.tar.gz"
      sha256 "d1c2de8c12d2c745dffb71d21a9db539368b997c86f60231be6f250bed61bdf0"
      def install
        bin.install "dogsay"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/dogsay
    EOS
  end

  test do
    system "#{bin}/dogsay version"
  end
end
