# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dogsay < Formula
  desc "dogsay"
  homepage "https://github.com/sikalabs/dogsay"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/dogsay/releases/download/v0.2.0/dogsay_v0.2.0_darwin_amd64.tar.gz"
      sha256 "535167782d8de1445d2520fac85373af8eaccaf176fb522f5009919cf9d15c77"

      def install
        bin.install "dogsay"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/dogsay/releases/download/v0.2.0/dogsay_v0.2.0_darwin_arm64.tar.gz"
      sha256 "bc127a58243b1062784ae62ba7c87e121c5382a070952a9104a250b7c614119e"

      def install
        bin.install "dogsay"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/dogsay/releases/download/v0.2.0/dogsay_v0.2.0_linux_amd64.tar.gz"
      sha256 "194e1b4261bf6f3b142d77e0503a8b102ffbbbb73764fd94dc6b9cf5bc55d5a9"
      def install
        bin.install "dogsay"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/dogsay/releases/download/v0.2.0/dogsay_v0.2.0_linux_arm64.tar.gz"
      sha256 "10a044224a5f5cb8180507e1f6ddb1fa7ea2558fc53af292275a9d8337668b5e"
      def install
        bin.install "dogsay"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/dogsay
    EOS
  end

  test do
    system "#{bin}/dogsay version"
  end
end
