# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gobble < Formula
  desc "gobble"
  homepage "https://github.com/sikalabs/gobble"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/gobble/releases/download/v0.2.0/gobble_v0.2.0_darwin_arm64.tar.gz"
      sha256 "bdf1dd80dc58739c08a0915331c1265108e8e2f46e222617905ca8c4264a97b5"

      def install
        bin.install "gobble"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/gobble/releases/download/v0.2.0/gobble_v0.2.0_darwin_amd64.tar.gz"
      sha256 "c67c41fbd1ec712ffa4f6a050ee18d1955db21694429f3f14724786a45a7111b"

      def install
        bin.install "gobble"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/gobble/releases/download/v0.2.0/gobble_v0.2.0_linux_arm64.tar.gz"
      sha256 "36d6d6add5355c8d681addc8aafe685d8f1080d99ec7cf6317a1f59460991807"

      def install
        bin.install "gobble"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/gobble/releases/download/v0.2.0/gobble_v0.2.0_linux_amd64.tar.gz"
      sha256 "be1f208c0a9006aeb42f8467791223216f1cd10850e170322f530bbde9cb10ed"

      def install
        bin.install "gobble"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/gobble
    EOS
  end

  test do
    system "#{bin}/gobble version"
  end
end
