# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Goexpandenv < Formula
  desc "goexpandenv is a simple CLI tool for expanding environment variables in files"
  homepage "https://github.com/sikalabs/goexpandenv"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/goexpandenv/releases/download/v0.1.0/goexpandenv_v0.1.0_darwin_arm64.tar.gz"
      sha256 "dd0f91c55937bc76d26ff1a569e6e0cc1b53dc3bd7137680aba890e8c3f01c0e"

      def install
        bin.install "goexpandenv"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/goexpandenv/releases/download/v0.1.0/goexpandenv_v0.1.0_darwin_amd64.tar.gz"
      sha256 "e4518f5fa0505aca931087ed29c7ec6c8ebb7a6ed5ba55da4c52c7ad2273314a"

      def install
        bin.install "goexpandenv"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/goexpandenv/releases/download/v0.1.0/goexpandenv_v0.1.0_linux_amd64.tar.gz"
      sha256 "ea29f05927dc55580f81a22be21dab9745a11427c607bc9d43b2dc3d94b56f22"

      def install
        bin.install "goexpandenv"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/goexpandenv/releases/download/v0.1.0/goexpandenv_v0.1.0_linux_arm64.tar.gz"
      sha256 "afc9b824923ad1b996ff4cf4d7304ebb1fd33149ee104754c589248024dbdc83"

      def install
        bin.install "goexpandenv"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/goexpandenv
    EOS
  end
end
