# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InstallSlu < Formula
  desc "install-slu"
  homepage "https://github.com/sikalabs/install-slu"
  version "0.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/install-slu/releases/download/v0.1.0/install-slu_v0.1.0_darwin_amd64.tar.gz"
      sha256 "f050817a259cfeafe291e67fe6461b3dab7c7e45ab79d6bb95e33aca8a641993"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/install-slu/releases/download/v0.1.0/install-slu_v0.1.0_darwin_arm64.tar.gz"
      sha256 "5cf41ca708ab1d326d161195063d465a9122d84d27b0af202a9943f595ecc395"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/install-slu/releases/download/v0.1.0/install-slu_v0.1.0_linux_amd64.tar.gz"
      sha256 "fabf9d07c5cea96331f1b618fbf3dc1cfb0483962e19e88254417f9b42057d27"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/install-slu/releases/download/v0.1.0/install-slu_v0.1.0_linux_arm64.tar.gz"
      sha256 "7f418d97a2457c21e2f4ecc91e05b9529d0019f02f51a5e0763fad1bd9f0003a"
    end
  end

  conflicts_with "install-slu-edge"

  def install
    bin.install "install-slu"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sikalabs/install-slu
  EOS
  end

  test do
    system "#{bin}/install-slu version"
  end
end
