# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InstallSlu < Formula
  desc "install-slu"
  homepage "https://github.com/sikalabs/install-slu"
  version "0.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/install-slu/releases/download/v0.1.0/install-slu_v0.1.0_darwin_amd64.tar.gz"
      sha256 "b8f775a67b2a6a3a8e522770d9198d3ab3a58f265e9df41e459cc9068216ad20"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/install-slu/releases/download/v0.1.0/install-slu_v0.1.0_darwin_arm64.tar.gz"
      sha256 "ab5b0856ee5f46a282a9ef799eaae4cfa0693c1b8cd48176526832c8bd8a33a8"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/install-slu/releases/download/v0.1.0/install-slu_v0.1.0_linux_amd64.tar.gz"
      sha256 "9b58735c414289519631b421f6a69f4e9ee6a473301abda0dd3fc00ed369449d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/install-slu/releases/download/v0.1.0/install-slu_v0.1.0_linux_arm64.tar.gz"
      sha256 "bcd6620fb4cb156c8bc7b531e2e8bc487fc0227a24e822237ff4bd2a3b81a3af"
    end
  end

  conflicts_with "install-slu-edge"

  def install
    bin.install "install-slu"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sikalabs/install-slu
  EOS
  end

  test do
    system "#{bin}/install-slu version"
  end
end
