# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class InstallSlu < Formula
  desc "install-slu"
  homepage "https://github.com/sikalabs/install-slu"
  version "0.1.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/install-slu/releases/download/v0.1.0/install-slu_v0.1.0_darwin_amd64.tar.gz"
      sha256 "ec8644dfbc1d5b528d577c27a7507b5f088d6abfafa40727839ae994e1f14b47"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/install-slu/releases/download/v0.1.0/install-slu_v0.1.0_darwin_arm64.tar.gz"
      sha256 "e846b555c4cfd2d4bb343579f4e8d4dc014ed6a97c9c2ad4f4f50f7a121bb010"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/install-slu/releases/download/v0.1.0/install-slu_v0.1.0_linux_amd64.tar.gz"
      sha256 "48a6291eb25ad13737f303a00859d0fc196a02b38039724dab0f48f4fcf84a78"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/install-slu/releases/download/v0.1.0/install-slu_v0.1.0_linux_arm64.tar.gz"
      sha256 "f662826c8fdbd652ded88cd183cca24abbb49c793a2652a0c92321495faf6fbb"
    end
  end

  conflicts_with "install-slu-edge"

  def install
    bin.install "install-slu"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sikalabs/install-slu
  EOS
  end

  test do
    system "#{bin}/install-slu version"
  end
end
