# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mon < Formula
  desc "mon"
  homepage "https://github.com/sikalabs/mon"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/mon/releases/download/v0.2.0/mon_v0.2.0_darwin_amd64.tar.gz"
      sha256 "18324676af6764b0fcafa43570bde9bd177185b5db1424f976d6a62164281f42"

      def install
        bin.install "mon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/mon/releases/download/v0.2.0/mon_v0.2.0_darwin_arm64.tar.gz"
      sha256 "741b6c6ccac20c1fc492add5f948aafaaa918f5a5245286c7a405fe271124786"

      def install
        bin.install "mon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/mon/releases/download/v0.2.0/mon_v0.2.0_linux_amd64.tar.gz"
      sha256 "dddee517b99ede1e5434995490a3b13ca69e0d4b46a51e3e374517857e084a06"
      def install
        bin.install "mon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/mon/releases/download/v0.2.0/mon_v0.2.0_linux_arm64.tar.gz"
      sha256 "04b634cbf2f3bd7bc21e14d3d172404e6cf4af511b57051cf9ebed5ea56f7a75"
      def install
        bin.install "mon"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/mon
    EOS
  end

  test do
    system "#{bin}/mon version"
  end
end
