# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mon < Formula
  desc "mon"
  homepage "https://github.com/sikalabs/mon"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/mon/releases/download/v0.1.0/mon_v0.1.0_darwin_amd64.tar.gz"
      sha256 "d5818b17f7b2a1f8a2e47b581f6d32adbf21f5a93144af727e56b3908b869b70"

      def install
        bin.install "mon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/mon/releases/download/v0.1.0/mon_v0.1.0_darwin_arm64.tar.gz"
      sha256 "e49b6469be30c78e1b9c1f0ab238737d04e0002735b38e7882d6c32007f9339d"

      def install
        bin.install "mon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/mon/releases/download/v0.1.0/mon_v0.1.0_linux_amd64.tar.gz"
      sha256 "2904b7898a2ac107816baa0e20094d1dcb960f57e9e36e696e0812ef8dd2e7e5"
      def install
        bin.install "mon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/mon/releases/download/v0.1.0/mon_v0.1.0_linux_arm64.tar.gz"
      sha256 "ac743ea77b9dc1e7f6d53ed5664d40d740dd9deee5e23dc819e19bed9fc27e33"
      def install
        bin.install "mon"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/mon
    EOS
  end

  test do
    system "#{bin}/mon version"
  end
end
