# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nela < Formula
  desc "nela"
  homepage "https://github.com/ondrejsika/nela-cli"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/nela-cli/releases/download/v0.2.0/nela_v0.2.0_darwin_amd64.tar.gz"
      sha256 "5cca4129f48574f25ba5eb58ac6541a059df961962ba9fc380f74b350f249d05"

      def install
        bin.install "nela"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/nela-cli/releases/download/v0.2.0/nela_v0.2.0_darwin_arm64.tar.gz"
      sha256 "4b78b4d7b6b488e68b63d34a4c8183cad1b22bf24fb0f0056dc1b85b126b66b1"

      def install
        bin.install "nela"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/nela-cli/releases/download/v0.2.0/nela_v0.2.0_linux_arm64.tar.gz"
      sha256 "f3c4a1c5b1506dd939573b9b59eed8ea530f459102e45f428e6f72e8a4f746c2"

      def install
        bin.install "nela"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/nela-cli/releases/download/v0.2.0/nela_v0.2.0_linux_amd64.tar.gz"
      sha256 "0ec694f1115f18efbda8d98a92fdc8822212a09435feb3a5e980247aac8c8990"

      def install
        bin.install "nela"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsika/nela-cli
    EOS
  end

  test do
    system "#{bin}/nela version"
  end
end
