# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Nela < Formula
  desc "nela"
  homepage "https://github.com/ondrejsika/nela-cli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/ondrejsika/nela-cli/releases/download/v0.1.0/nela_v0.1.0_darwin_arm64.tar.gz"
      sha256 "e81bc53886a4273e5be619c190294e41cf546a9c6ce602f63afe5f98860705f8"

      def install
        bin.install "nela"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/nela-cli/releases/download/v0.1.0/nela_v0.1.0_darwin_amd64.tar.gz"
      sha256 "ddd45ab2d35d50f1baefc56448207d6b3d424cdb6b09546bf75d301db945816d"

      def install
        bin.install "nela"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/ondrejsika/nela-cli/releases/download/v0.1.0/nela_v0.1.0_linux_amd64.tar.gz"
      sha256 "b0e1660cc24fa7c1767cc2329a1f91f95e650cc7094abc837189b543bc8747d9"

      def install
        bin.install "nela"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ondrejsika/nela-cli/releases/download/v0.1.0/nela_v0.1.0_linux_arm64.tar.gz"
      sha256 "b4073d65af5b21b27f6947c082ada02494a6e89e3adcb46bb063984cffae72ea"

      def install
        bin.install "nela"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/ondrejsika/nela-cli
    EOS
  end

  test do
    system "#{bin}/nela version"
  end
end
