# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Signpost < Formula
  desc "signpost"
  homepage "https://github.com/sikalabs/signpost"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/signpost/releases/download/v0.3.0/signpost_v0.3.0_darwin_arm64.tar.gz"
      sha256 "e85c61e2f1f9cd8469473ef8f8da2491a99dc552862c51831fd8f58c90b5f6f4"

      def install
        bin.install "signpost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/signpost/releases/download/v0.3.0/signpost_v0.3.0_darwin_amd64.tar.gz"
      sha256 "d74b94cdf5bb112a6e2cb849c8f5cd92a9de72622cb371a02b0bd4435783d7f7"

      def install
        bin.install "signpost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/signpost/releases/download/v0.3.0/signpost_v0.3.0_linux_arm64.tar.gz"
      sha256 "471782948500ed5a5818ece8d674d50809d68b0cad9753e21c63545ebc55ef38"

      def install
        bin.install "signpost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/signpost/releases/download/v0.3.0/signpost_v0.3.0_linux_amd64.tar.gz"
      sha256 "b2d87f3bb58ee10582d08dd42cdb92e3690b557483a9aaa89df16fc82f030f33"

      def install
        bin.install "signpost"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/signpost
    EOS
  end

  test do
    system "#{bin}/signpost version"
  end
end
