# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Signpost < Formula
  desc "signpost"
  homepage "https://github.com/sikalabs/signpost"
  version "0.6.0"

  on_macos do
    on_intel do
      url "https://github.com/sikalabs/signpost/releases/download/v0.6.0/signpost_v0.6.0_darwin_amd64.tar.gz"
      sha256 "ca74b2d7688e53788f335f6a300e69eb1cdfff672eef81f081dea3853fb4ca9c"

      def install
        bin.install "signpost"
      end
    end
    on_arm do
      url "https://github.com/sikalabs/signpost/releases/download/v0.6.0/signpost_v0.6.0_darwin_arm64.tar.gz"
      sha256 "2f5b2cb9bcfce14af3c926b5f6da8858863bf83ef407d5fc8d9d499d8a31269b"

      def install
        bin.install "signpost"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sikalabs/signpost/releases/download/v0.6.0/signpost_v0.6.0_linux_amd64.tar.gz"
        sha256 "fb6be98fa2a60c7a28be0b88f37c3d2ea950fe0e05bce887763014be83fdb5bf"

        def install
          bin.install "signpost"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sikalabs/signpost/releases/download/v0.6.0/signpost_v0.6.0_linux_arm64.tar.gz"
        sha256 "ac209723cde0f9582de24803b90f35d5ef6871f2fa8e6460366d786af097d3df"

        def install
          bin.install "signpost"
        end
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/signpost
    EOS
  end

  test do
    system "#{bin}/signpost version"
  end
end
