# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Signpost < Formula
  desc "signpost"
  homepage "https://github.com/sikalabs/signpost"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/signpost/releases/download/v0.1.0/signpost_v0.1.0_darwin_arm64.tar.gz"
      sha256 "c6cd3204a702b76c6ed7eb2da38d7ed5f9be85f598681c2db06fd572d1777311"

      def install
        bin.install "signpost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/signpost/releases/download/v0.1.0/signpost_v0.1.0_darwin_amd64.tar.gz"
      sha256 "68830dade5aac417ac59ef22b29edf16447c4c8e425ccd70d931761b7b77c3f6"

      def install
        bin.install "signpost"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/signpost/releases/download/v0.1.0/signpost_v0.1.0_linux_arm64.tar.gz"
      sha256 "97a4778286c30beec09786e1843974f30db71a57a50efdf28c50a4d7a8922299"

      def install
        bin.install "signpost"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/signpost/releases/download/v0.1.0/signpost_v0.1.0_linux_amd64.tar.gz"
      sha256 "c54e42b4113dc5a44eb424bbd7acda43c41e443d187af282e3e5e6e963e905ed"

      def install
        bin.install "signpost"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/signpost
    EOS
  end

  test do
    system "#{bin}/signpost version"
  end
end
