# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SikalabsKubernetesOidcLogin < Formula
  desc "sikalabs-kubernetes-oidc-login is a simple command-line tool that performs OIDC login and outputs Kubernetes ExecCredential for kubectl. It allows users to authenticate with an OIDC provider and obtain the necessary credentials to access Kubernetes clusters."
  homepage "https://github.com/sikalabs/sikalabs-kubernetes-oidc-login"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/sikalabs-kubernetes-oidc-login/releases/download/v0.1.0/sikalabs-kubernetes-oidc-login_v0.1.0_darwin_amd64.tar.gz"
      sha256 "388b10191642562b8aae9f89f90c415e2f6f039e50e5085b2522869a7f908799"

      def install
        bin.install "sikalabs-kubernetes-oidc-login"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/sikalabs-kubernetes-oidc-login/releases/download/v0.1.0/sikalabs-kubernetes-oidc-login_v0.1.0_darwin_arm64.tar.gz"
      sha256 "63809c49ea93f337cc313e8180b759d6360ff3b576a0d5329a8f6008206b22e3"

      def install
        bin.install "sikalabs-kubernetes-oidc-login"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/sikalabs-kubernetes-oidc-login/releases/download/v0.1.0/sikalabs-kubernetes-oidc-login_v0.1.0_linux_amd64.tar.gz"
      sha256 "72e729b2537f52f15ef117eabcfe51d49635e6cc816550fda2bddad8c86866ef"
      def install
        bin.install "sikalabs-kubernetes-oidc-login"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/sikalabs-kubernetes-oidc-login/releases/download/v0.1.0/sikalabs-kubernetes-oidc-login_v0.1.0_linux_arm64.tar.gz"
      sha256 "f394ee8fc27bf35d1e1732f8db0953be48f7696a21a825af05134c122d7fe28d"
      def install
        bin.install "sikalabs-kubernetes-oidc-login"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/sikalabs-kubernetes-oidc-login
    EOS
  end

  test do
    system "#{bin}/sikalabs-kubernetes-oidc-login version"
  end
end
