# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slc < Formula
  desc "SikaLabs Cloud CLI"
  homepage "https://github.com/sikalabs/slc"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/slc/releases/download/v0.1.0/slc_v0.1.0_darwin_arm64.tar.gz"
      sha256 "aba01c4eb8b9a606b855af7aafcfc4fd13df4db10b8e885a55720a250325a957"

      def install
        bin.install "slc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/slc/releases/download/v0.1.0/slc_v0.1.0_darwin_amd64.tar.gz"
      sha256 "2a200cc740be8e1be3c0cb42aa1cfe3a89df09ae0137c6e01ccf85282453e56e"

      def install
        bin.install "slc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/slc/releases/download/v0.1.0/slc_v0.1.0_linux_arm64.tar.gz"
      sha256 "5407ac1738e2bea4b2d1e6af994e7ea1e538a0e7b1673e85fda01140536df399"

      def install
        bin.install "slc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/slc/releases/download/v0.1.0/slc_v0.1.0_linux_amd64.tar.gz"
      sha256 "b7e9a74ab52b62ff8e21606e4d2ae4e313f966a7e6136f5d3f20561c66a31d99"

      def install
        bin.install "slc"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/slc
    EOS
  end

  test do
    system "#{bin}/slc version"
  end
end
