# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sli < Formula
  desc "sli"
  homepage "https://github.com/sikalabs/sli"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/sli/releases/download/v0.1.0/sli_v0.1.0_darwin_amd64.tar.gz"
      sha256 "abf15b5138977749ef4175ba6a5fe70caf6553a204126ed89ecbff2d53e71cdd"

      def install
        bin.install "sli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/sli/releases/download/v0.1.0/sli_v0.1.0_darwin_arm64.tar.gz"
      sha256 "f03e6d240daf1d113cee88f9e570eab177d517f71225479afbbff72248180e05"

      def install
        bin.install "sli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/sli/releases/download/v0.1.0/sli_v0.1.0_linux_amd64.tar.gz"
      sha256 "aef7db1434363867ca9fc7558c37df442bfccf1c2c6718499a062445dfa59167"
      def install
        bin.install "sli"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/sli/releases/download/v0.1.0/sli_v0.1.0_linux_arm64.tar.gz"
      sha256 "e2eea1cf7318b04d43b03d482f6fa2cf1a06c6cfaa50f1ae0c5ca421a06eb8ab"
      def install
        bin.install "sli"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/sli
    EOS
  end

  test do
    system "#{bin}/sli version"
  end
end
