# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slr < Formula
  desc "slr"
  homepage "https://github.com/sikalabs/slr"
  version "0.5.0"

  on_macos do
    on_intel do
      url "https://github.com/sikalabs/slr/releases/download/v0.5.0/slr_v0.5.0_darwin_amd64.tar.gz"
      sha256 "649edc504dca6c7bac68a4e266bb34a9d70f80fa1919536bf2775c79f7b6d749"

      def install
        bin.install "slr"
      end
    end
    on_arm do
      url "https://github.com/sikalabs/slr/releases/download/v0.5.0/slr_v0.5.0_darwin_arm64.tar.gz"
      sha256 "4e43f8891018d79d9c794075f916303eb82bd50db0e383ffc6931affb18256bc"

      def install
        bin.install "slr"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sikalabs/slr/releases/download/v0.5.0/slr_v0.5.0_linux_amd64.tar.gz"
        sha256 "3cfcc788112babc8351da76f696670289c4edc0669eb18cb79fba17ae4769db7"

        def install
          bin.install "slr"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/sikalabs/slr/releases/download/v0.5.0/slr_v0.5.0_linux_arm64.tar.gz"
        sha256 "d3b435f5fbd4cfc464e9abd232d5af780671779d1ea936cbeff1e6291630e735"

        def install
          bin.install "slr"
        end
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/slr
    EOS
  end

  test do
    system "#{bin}/slr version"
  end
end
