# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SluEdge < Formula
  desc "SikaLabs Utils"
  homepage "https://github.com/sikalabs/slu"
  version "0.33.0-dev-3"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/slu/releases/download/v0.33.0-dev-3/slu_v0.33.0-dev-3_darwin_arm64.tar.gz"
      sha256 "7ebb6b704c1bf8c007de19ab210c4d8a760e9b4f6dfe8622cda1b3dcb4afa6d4"

      def install
        bin.install "slu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/slu/releases/download/v0.33.0-dev-3/slu_v0.33.0-dev-3_darwin_amd64.tar.gz"
      sha256 "52199e5cb9e926a563f998bab9e90418a1497ac9f0c6f7b66931cef4225724aa"

      def install
        bin.install "slu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/slu/releases/download/v0.33.0-dev-3/slu_v0.33.0-dev-3_linux_arm64.tar.gz"
      sha256 "8a32d5bc83f04c2636f564b3932c870e1ccc2ed55b1268b83b7e27616596ced1"

      def install
        bin.install "slu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/slu/releases/download/v0.33.0-dev-3/slu_v0.33.0-dev-3_linux_amd64.tar.gz"
      sha256 "f82ca8498ef7b73d394706fbf8a352907a550b7a3a38140b304fdb88da7c8887"

      def install
        bin.install "slu"
      end
    end
  end

  conflicts_with "slu"

  def caveats; <<~EOS
    How to use this binary: https://github.com/sikalabs/slu
  EOS
  end

  test do
    system "#{bin}/slu version"
  end
end
