# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SluEdge < Formula
  desc "SikaLabs Utils"
  homepage "https://github.com/sikalabs/slu"
  version "0.10.0-dev-5"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/sikalabs/slu/releases/download/v0.10.0-dev-5/slu_v0.10.0-dev-5_darwin_amd64.tar.gz"
    sha256 "d325d5ab247fdb059967e41bbd756e75182306ddb7a0ad1705526f41419d62a9"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/sikalabs/slu/releases/download/v0.10.0-dev-5/slu_v0.10.0-dev-5_darwin_arm64.tar.gz"
    sha256 "5b74868dbda61d3647a0b52aaa91e4a7e09f7b67c82a0147950f2309b0f7b2ca"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sikalabs/slu/releases/download/v0.10.0-dev-5/slu_v0.10.0-dev-5_linux_amd64.tar.gz"
    sha256 "e16da66f4714947cdef369761beac3ca939f8dec51c79311d60afff065f49339"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/sikalabs/slu/releases/download/v0.10.0-dev-5/slu_v0.10.0-dev-5_linux_arm64.tar.gz"
    sha256 "df09bb21aa6056525db88dbef2a6932aad10b360bb64c583df271532d941402d"
  end

  conflicts_with "slu"

  def install
    bin.install "slu"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sikalabs/slu
  EOS
  end

  test do
    system "#{bin}/slu version"
  end
end
