# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slu < Formula
  desc "SikaLabs Utils"
  homepage "https://github.com/sikalabs/slu"
  version "0.64.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/slu/releases/download/v0.64.0/slu_v0.64.0_darwin_arm64.tar.gz"
      sha256 "9922435fa56876e665bee03ef0afb9fba73761036bdf3fc0f19bf8f8e500fbdd"

      def install
        bin.install "slu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/slu/releases/download/v0.64.0/slu_v0.64.0_darwin_amd64.tar.gz"
      sha256 "bbd51093bd5ae4dfedebcb94f6af166b0da452edad40b6f6fd56e0e19a9b4600"

      def install
        bin.install "slu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/slu/releases/download/v0.64.0/slu_v0.64.0_linux_arm64.tar.gz"
      sha256 "b3dbbba96287ec68ebb4f93d3052bbfde66035892ec48a763ecfb30ed5f00bab"

      def install
        bin.install "slu"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/slu/releases/download/v0.64.0/slu_v0.64.0_linux_amd64.tar.gz"
      sha256 "6d3722e99087a17a23f6fb48e788c4acc1f99d1ba189c1d5113dd5a23a2086b5"

      def install
        bin.install "slu"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/slu
    EOS
  end

  test do
    system "#{bin}/slu version"
  end
end
