# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SluATedge < Formula
  desc "SikaLabs Utils"
  homepage "https://github.com/sikalabs/slu"
  version "0.11.0-dev-3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-3/slu_v0.11.0-dev-3_darwin_amd64.tar.gz"
      sha256 "3ec79ab1ee2f85f3c87f4b44b3d4477048066ead3d0f20e9048fdbfdac98a886"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-3/slu_v0.11.0-dev-3_darwin_arm64.tar.gz"
      sha256 "1d6a6ad28084d98a69e8b9c20efdb2ac8c81706c1ee85518a5d3136347f9d2de"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-3/slu_v0.11.0-dev-3_linux_amd64.tar.gz"
      sha256 "dd9fb00a0673e3ff311bc55b99c404989e78b3ea3868d247347b417bdc67d10d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-3/slu_v0.11.0-dev-3_linux_arm64.tar.gz"
      sha256 "266a1d835e0547687377db8abf03c686d7bf1f161f6634ef0deb4e621150053b"
    end
  end

  keg_only :versioned_formula

  def install
    bin.install "slu"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sikalabs/slu
  EOS
  end

  test do
    system "#{bin}/slu version"
  end
end
