# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SluAT1 < Formula
  desc "SikaLabs Utils"
  homepage "https://github.com/sikalabs/slu"
  version "0.11.0-dev-4"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-4/slu_v0.11.0-dev-4_darwin_amd64.tar.gz"
      sha256 "4d7c18e7b91ed43fc06eb176cf32a249771585f88b7be270cd91fce3eb3ba8d8"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-4/slu_v0.11.0-dev-4_darwin_arm64.tar.gz"
      sha256 "f7773ff627ee865c1d80177466c8d64f9749f2d01be79c14a71aaf2d48bae65b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-4/slu_v0.11.0-dev-4_linux_amd64.tar.gz"
      sha256 "88fa084bba77a0d4fddaae1849d0d2678bfb76b51ea4ea57f052b687063bbfcd"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-4/slu_v0.11.0-dev-4_linux_arm64.tar.gz"
      sha256 "acc432ad1f56c0aae6876b072244fb8509386a0c1b81667e0267204dfe490a7b"
    end
  end

  keg_only :versioned_formula

  def install
    bin.install "slu"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sikalabs/slu
  EOS
  end

  test do
    system "#{bin}/slu version"
  end
end
