# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SluATedge < Formula
  desc "SikaLabs Utils"
  homepage "https://github.com/sikalabs/slu"
  version "0.11.0-dev-1"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-1/slu_v0.11.0-dev-1_darwin_amd64.tar.gz"
    sha256 "66515b210a5599040c9cfb9a5bd670a18293528ac0c0388813c78e2c6c929db5"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-1/slu_v0.11.0-dev-1_darwin_arm64.tar.gz"
    sha256 "5d938fcd4e8717e770a30eff0b75b736d19817658ecab43444a5e345b61bc0d5"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-1/slu_v0.11.0-dev-1_linux_amd64.tar.gz"
    sha256 "e4898729ce6fa69d1b15fdc4ee0804304393c98dc962ee9e53426af841424d82"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-1/slu_v0.11.0-dev-1_linux_arm64.tar.gz"
    sha256 "e5fbf300d56f3655ba95b066ad1769a3f7abb487030727be506e5ea1790c9749"
  end

  conflicts_with "slu"

  def install
    bin.install "slu"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sikalabs/slu
  EOS
  end

  test do
    system "#{bin}/slu version"
  end
end
