# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SluATedge < Formula
  desc "SikaLabs Utils"
  homepage "https://github.com/sikalabs/slu"
  version "0.11.0-dev-2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-2/slu_v0.11.0-dev-2_darwin_amd64.tar.gz"
      sha256 "f5f26f1b4e9a419510b38ff798ca59318ec6079eecccf48f4f3e9d44afa118ce"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-2/slu_v0.11.0-dev-2_darwin_arm64.tar.gz"
      sha256 "8ddfcf74389b03e426d4a364c8fab841ee882db7f68dfb6168a2ba15f57abc34"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-2/slu_v0.11.0-dev-2_linux_amd64.tar.gz"
      sha256 "1113c1dee4d3b5bbdfdf1458d5c3dbc6eb30837840362ac99927fe5b8c3cc2ca"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/slu/releases/download/v0.11.0-dev-2/slu_v0.11.0-dev-2_linux_arm64.tar.gz"
      sha256 "4df59656f0e44da1d4c15d0209414a6846ad05ad45e13dae55797955b035f5f1"
    end
  end

  def install
    bin.install "slu"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sikalabs/slu
  EOS
  end

  test do
    system "#{bin}/slu version"
  end
end
