# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Slut < Formula
  desc "SikaLabs Utils"
  homepage "https://github.com/sikalabs/slut"
  version "0.1.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/sikalabs/slut/releases/download/v0.1.0/slut_0.1.0_darwin_amd64.tar.gz"
    sha256 "1867be0719e464a8fcd65448e0cbc06674c4947811fdf60df8dd1b268a489df9"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/sikalabs/slut/releases/download/v0.1.0/slut_0.1.0_darwin_arm64.tar.gz"
    sha256 "85a9ddab4709bed66c864d8a73f7a2229ea5b0586aa78bf3eacb7b8f2dfc1402"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/sikalabs/slut/releases/download/v0.1.0/slut_0.1.0_linux_amd64.tar.gz"
    sha256 "945996a3c5fadfe46543ecf6793f3fdff24fba6e4bcb3cb96e3cbbd3b0a2598d"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/sikalabs/slut/releases/download/v0.1.0/slut_0.1.0_linux_arm64.tar.gz"
    sha256 "9661e4ddd65ed4f804f92f5651bcf5b5af7fd4eab656f1a8ac21e24fbf4f2b3a"
  end

  def install
    bin.install "slut"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sikalabs/slut
  EOS
  end

  test do
    system "#{bin}/slut version"
  end
end
