# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TergumTelemetry < Formula
  desc "tergum-telemetry"
  homepage "https://github.com/sikalabs/tergum-telemetry"
  version "0.2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/tergum-telemetry/releases/download/v0.2.0/tergum-telemetry_v0.2.0_darwin_amd64.tar.gz"
      sha256 "aaf25702ec8d2ddd80a027ce7996e29137f1e47ee16abd4e0f0542f568ec5f5c"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/tergum-telemetry/releases/download/v0.2.0/tergum-telemetry_v0.2.0_darwin_arm64.tar.gz"
      sha256 "0b6ec0133c097cf2254770f07bfa1d971fb92d1a23ee62d70d9f03b833dd3a5d"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/tergum-telemetry/releases/download/v0.2.0/tergum-telemetry_v0.2.0_linux_amd64.tar.gz"
      sha256 "93a8a230b02f430bcf794bbedc884acf403cf903d2742f997365890a86e1cf13"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/tergum-telemetry/releases/download/v0.2.0/tergum-telemetry_v0.2.0_linux_arm64.tar.gz"
      sha256 "b048d467ebb627262b80fac34d38eb8c299bdc7025e7a6767e58bf8a68a72769"
    end
  end

  def install
    bin.install "tergum-telemetry"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sikalabs/tergum-telemetry
  EOS
  end

  test do
    system "#{bin}/tergum-telemetry version"
  end
end
