# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tergum < Formula
  desc "Tergum Backup Tool"
  homepage "https://github.com/sikalabs/tergum"
  version "0.40.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/tergum/releases/download/v0.40.0/tergum_v0.40.0_darwin_amd64.tar.gz"
      sha256 "6f9d39e67a926289b72a31a609058f13f6973bd83fa61fc937e340f751d66777"

      def install
        bin.install "tergum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/tergum/releases/download/v0.40.0/tergum_v0.40.0_darwin_arm64.tar.gz"
      sha256 "6594188e11b4fb91472641204f4cb787e4303f82eb8df6368e58b8e04aaeb199"

      def install
        bin.install "tergum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/tergum/releases/download/v0.40.0/tergum_v0.40.0_linux_amd64.tar.gz"
      sha256 "498e1a4d49fe99bba6e6cc00719a8398b34e8fa4aa00163e1f6e5a58071a9890"
      def install
        bin.install "tergum"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/tergum/releases/download/v0.40.0/tergum_v0.40.0_linux_arm64.tar.gz"
      sha256 "45a6455fbb5252a6eb424170829d586bbad815945a919596e77f10434a5563cc"
      def install
        bin.install "tergum"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/tergum
    EOS
  end

  test do
    system "#{bin}/tergum version"
  end
end
