# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TergumTelemetryServerEdge < Formula
  desc "tergum-telemetry-server"
  homepage "https://github.com/sikalabs/tergum-telemetry-server"
  version "0.1.0-dev-1"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/tergum-telemetry-server/releases/download/v0.1.0-dev-1/tergum-telemetry-server_v0.1.0-dev-1_darwin_amd64.tar.gz"
      sha256 "d7b8a8b6f5719d63567f59847af7f2639540fc54b09dabe608a44660ccf7725e"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/tergum-telemetry-server/releases/download/v0.1.0-dev-1/tergum-telemetry-server_v0.1.0-dev-1_darwin_arm64.tar.gz"
      sha256 "c369ed3233a0bf494e576da07545c3a3a503db96133f95456508f1f4a0dfd674"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/tergum-telemetry-server/releases/download/v0.1.0-dev-1/tergum-telemetry-server_v0.1.0-dev-1_linux_amd64.tar.gz"
      sha256 "1b4eacdf49046bd7d94b0a72dd3f45fb7dd089255a0327757ef4f8054ae1e5e6"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/tergum-telemetry-server/releases/download/v0.1.0-dev-1/tergum-telemetry-server_v0.1.0-dev-1_linux_arm64.tar.gz"
      sha256 "d5c2ffc6df8143b429cdfe81a31976e6a93f4afae5c42449ba402b5d141c2e9e"
    end
  end

  conflicts_with "tergum-telemetry-server"

  def install
    bin.install "tergum-telemetry-server"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sikalabs/tergum-telemetry-server
  EOS
  end

  test do
    system "#{bin}/tergum-telemetry-server version"
  end
end
