# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tergum < Formula
  desc "Tergum Backup Tool"
  homepage "https://github.com/sikalabs/tergum"
  version "0.43.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/tergum/releases/download/v0.43.0/tergum_v0.43.0_darwin_amd64.tar.gz"
      sha256 "914f7f8f5805aed99228a818181736f60d28cba5b13d2cbbef755d3bce080172"

      define_method(:install) do
        bin.install "tergum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/tergum/releases/download/v0.43.0/tergum_v0.43.0_darwin_arm64.tar.gz"
      sha256 "bdec51529318314e8a4ee01c19b11b6d74caa5bfb2a92c2fe0be91c6bbe1cbcd"

      define_method(:install) do
        bin.install "tergum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/tergum/releases/download/v0.43.0/tergum_v0.43.0_linux_amd64.tar.gz"
      sha256 "27c4e3b0baa912ac031e1aa53fb9f4540d643d45d14d9a8a4a4428b3a4d5e24e"
      define_method(:install) do
        bin.install "tergum"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/tergum/releases/download/v0.43.0/tergum_v0.43.0_linux_arm64.tar.gz"
      sha256 "7f230da6d781fbb8725b55de0bf61e4e63b39fb83654963af7883a8bc7b414cf"
      define_method(:install) do
        bin.install "tergum"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/tergum
    EOS
  end

  test do
    system "#{bin}/tergum version"
  end
end
