# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TergumEdge < Formula
  desc "Tergum Backup Tool"
  homepage "https://github.com/sikalabs/tergum"
  version "0.9.0-dev-3"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/tergum/releases/download/v0.9.0-dev-3/tergum_v0.9.0-dev-3_darwin_amd64.tar.gz"
      sha256 "6881feffc94ce46f6519a97b64389e24435323570b0f04f98d2f2ae4643c210b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/tergum/releases/download/v0.9.0-dev-3/tergum_v0.9.0-dev-3_darwin_arm64.tar.gz"
      sha256 "354b19fee156823c91d61b3b1a8951a8e1d6b35f70ff1d9e535bceda97278b65"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/tergum/releases/download/v0.9.0-dev-3/tergum_v0.9.0-dev-3_linux_amd64.tar.gz"
      sha256 "048e1da2dd6776cb21d1ce5cde425b0f4ae25be00369f6605f9bdd3ad7d7614c"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/tergum/releases/download/v0.9.0-dev-3/tergum_v0.9.0-dev-3_linux_arm64.tar.gz"
      sha256 "24acc93b59a07f6d2b66d88147b6d959458ea60a8d8ca21b251052f612f77791"
    end
  end

  conflicts_with "tergum"

  def install
    bin.install "tergum"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sikalabs/tergum
  EOS
  end

  test do
    system "#{bin}/tergum version"
  end
end
