# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tergum < Formula
  desc "Tergum Backup Tool"
  homepage "https://github.com/sikalabs/tergum"
  version "0.41.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/tergum/releases/download/v0.41.0/tergum_v0.41.0_darwin_amd64.tar.gz"
      sha256 "84ee90c88d7a78ad1e8b7524b61859c51e7430dada794d3b4e5d1638730c2299"

      def install
        bin.install "tergum"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/tergum/releases/download/v0.41.0/tergum_v0.41.0_darwin_arm64.tar.gz"
      sha256 "f24367d02fa06ea061d373a2f7144df49c057cb007d1f28ca85c982af1422a96"

      def install
        bin.install "tergum"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/tergum/releases/download/v0.41.0/tergum_v0.41.0_linux_amd64.tar.gz"
      sha256 "293a07132fe128392f3b1468cb7c1d77c5ad014569226bfe0bf44349d8412306"
      def install
        bin.install "tergum"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/tergum/releases/download/v0.41.0/tergum_v0.41.0_linux_arm64.tar.gz"
      sha256 "e795749969d9a8ecf9042f9d5b7b8f404880730382ba955feddfa01cf0e78cd1"
      def install
        bin.install "tergum"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/tergum
    EOS
  end

  test do
    system "#{bin}/tergum version"
  end
end
