# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TergumTelemetryServerEdge < Formula
  desc "tergum-telemetry-server"
  homepage "https://github.com/sikalabs/tergum-telemetry-server"
  version "0.1.0-dev-2"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/tergum-telemetry-server/releases/download/v0.1.0-dev-2/tergum-telemetry-server_v0.1.0-dev-2_darwin_amd64.tar.gz"
      sha256 "b7f483d3a7302ed770842abb10fbe6e653209ee1332ae1608bf6e3ec1ff9a186"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/tergum-telemetry-server/releases/download/v0.1.0-dev-2/tergum-telemetry-server_v0.1.0-dev-2_darwin_arm64.tar.gz"
      sha256 "9ba52f86ca04ad7a18b9a00377839ee04d69f7540333d309b436f70b578fea41"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/tergum-telemetry-server/releases/download/v0.1.0-dev-2/tergum-telemetry-server_v0.1.0-dev-2_linux_amd64.tar.gz"
      sha256 "f9537323e367dfb62d75fb9c77d0e33c26a47196436cb5135d1bb8d59675a7b8"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/tergum-telemetry-server/releases/download/v0.1.0-dev-2/tergum-telemetry-server_v0.1.0-dev-2_linux_arm64.tar.gz"
      sha256 "6f9e4328513bf7aecd436971835f984f3e71ac81df61fb0b78442f46b5a712b8"
    end
  end

  conflicts_with "tergum-telemetry-server"

  def install
    bin.install "tergum-telemetry-server"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sikalabs/tergum-telemetry-server
  EOS
  end

  test do
    system "#{bin}/tergum-telemetry-server version"
  end
end
