# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TergumTelemetry < Formula
  desc "tergum-telemetry"
  homepage "https://github.com/sikalabs/tergum-telemetry"
  version "0.4.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/tergum-telemetry/releases/download/v0.4.0/tergum-telemetry_v0.4.0_darwin_amd64.tar.gz"
      sha256 "d790bd39bca60f5ade2b652af4b701629267b8a0e2a27c871f100b704b6579a0"
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/tergum-telemetry/releases/download/v0.4.0/tergum-telemetry_v0.4.0_darwin_arm64.tar.gz"
      sha256 "4646b1e67be0b63c97a6d65eb9ca1008d5961b09266e4e8ce69cca3ad25fab1b"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/tergum-telemetry/releases/download/v0.4.0/tergum-telemetry_v0.4.0_linux_amd64.tar.gz"
      sha256 "ff8ef1df9eb211a73074584caadfb79923d0bc2a6a3f0fa8482a285324531e9e"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/tergum-telemetry/releases/download/v0.4.0/tergum-telemetry_v0.4.0_linux_arm64.tar.gz"
      sha256 "a98e806e9b5bc0d78ff5f4768a2ba8d2a5bf2bdace14a41ef4d898280fa9f37e"
    end
  end

  def install
    bin.install "tergum-telemetry"
  end

  def caveats; <<~EOS
    How to use this binary: https://github.com/sikalabs/tergum-telemetry
  EOS
  end

  test do
    system "#{bin}/tergum-telemetry version"
  end
end
