# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vali < Formula
  desc "vali"
  homepage "https://github.com/sikalabs/vali"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/vali/releases/download/v0.2.0/vali_v0.2.0_darwin_amd64.tar.gz"
      sha256 "ef78276ceb5207fbd599c1558267b035cd6623ac920dcde3c9a7886ba592ef09"

      define_method(:install) do
        bin.install "vali"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/vali/releases/download/v0.2.0/vali_v0.2.0_darwin_arm64.tar.gz"
      sha256 "803ab2b6dc645cd656e8d64a516df564769e3ea9355f762f11878ac9b232a1d0"

      define_method(:install) do
        bin.install "vali"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/vali/releases/download/v0.2.0/vali_v0.2.0_linux_amd64.tar.gz"
      sha256 "3963b4990228d0c6c4db6bdc177f22a6765f7436cd33c2e6bd6d81ac43c22720"
      define_method(:install) do
        bin.install "vali"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/vali/releases/download/v0.2.0/vali_v0.2.0_linux_arm64.tar.gz"
      sha256 "76c62f3ddfa457cbe386805a1e4cb5f30d87245773631170ba8141b8adcf0998"
      define_method(:install) do
        bin.install "vali"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/vali
    EOS
  end

  test do
    system "#{bin}/vali version"
  end
end
