# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Vali < Formula
  desc "vali"
  homepage "https://github.com/sikalabs/vali"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/vali/releases/download/v0.1.0/vali_v0.1.0_darwin_amd64.tar.gz"
      sha256 "041303ab8da91628230b1bcd6b3a5a37e9cbbe494c24aebb2b2a5c2ba7372446"

      define_method(:install) do
        bin.install "vali"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/vali/releases/download/v0.1.0/vali_v0.1.0_darwin_arm64.tar.gz"
      sha256 "6b1c7f65c7886fc5d92d878642341d52b768987c6dcad28cd72485889a7cbc0a"

      define_method(:install) do
        bin.install "vali"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/vali/releases/download/v0.1.0/vali_v0.1.0_linux_amd64.tar.gz"
      sha256 "d234d5330a5d282d64f89e9aeec9b963a3fa58a089f836a4f2fb3b6d94475fcc"
      define_method(:install) do
        bin.install "vali"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/vali/releases/download/v0.1.0/vali_v0.1.0_linux_arm64.tar.gz"
      sha256 "1315c4e1b36102db4c2cc91f5b40bb98ec6d7e349cd2d1bf2ce094f41e6f9cfc"
      define_method(:install) do
        bin.install "vali"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/vali
    EOS
  end

  test do
    system "#{bin}/vali version"
  end
end
