# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebhookDispatcher < Formula
  desc "webhook-dispatcher"
  homepage "https://github.com/sikalabs/webhook-dispatcher"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/webhook-dispatcher/releases/download/v0.3.0/webhook-dispatcher_v0.3.0_darwin_amd64.tar.gz"
      sha256 "3dc7dfa8e3a01818f73b924fe939ae6c2726d8f6d098187a941d07b5c6fe2717"

      def install
        bin.install "webhook-dispatcher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/webhook-dispatcher/releases/download/v0.3.0/webhook-dispatcher_v0.3.0_darwin_arm64.tar.gz"
      sha256 "fcbfaa51fbed3b6cde94d66af344f419ae283666fea2807263c7f158396b3a66"

      def install
        bin.install "webhook-dispatcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/webhook-dispatcher/releases/download/v0.3.0/webhook-dispatcher_v0.3.0_linux_amd64.tar.gz"
      sha256 "920cb09064f1036c663baff3ebe15a66fcd1a2c92d38e4c678457855c4e98c2e"
      def install
        bin.install "webhook-dispatcher"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/webhook-dispatcher/releases/download/v0.3.0/webhook-dispatcher_v0.3.0_linux_arm64.tar.gz"
      sha256 "037aae7c3b2e21aa2ee1d05648a073cb832154e439dd95f804a7ee79f002d8fc"
      def install
        bin.install "webhook-dispatcher"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/webhook-dispatcher
    EOS
  end

  test do
    system "#{bin}/webhook-dispatcher version"
  end
end
