# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebhookDispatcher < Formula
  desc "webhook-dispatcher"
  homepage "https://github.com/sikalabs/webhook-dispatcher"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/webhook-dispatcher/releases/download/v0.2.0/webhook-dispatcher_v0.2.0_darwin_amd64.tar.gz"
      sha256 "2587d95d60d9b90b20f295cdb9fee7d9ea8f8917172ec19bc713ae0a6b15d6bd"

      def install
        bin.install "webhook-dispatcher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/webhook-dispatcher/releases/download/v0.2.0/webhook-dispatcher_v0.2.0_darwin_arm64.tar.gz"
      sha256 "2117269316935279b79edb95dff6418662a11eac7eed25a7f4566217057d72b3"

      def install
        bin.install "webhook-dispatcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/webhook-dispatcher/releases/download/v0.2.0/webhook-dispatcher_v0.2.0_linux_amd64.tar.gz"
      sha256 "1e7220197edbcc79684f02757a43c1f8020dc4b0e99136eaa623b0c984a0c584"
      def install
        bin.install "webhook-dispatcher"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/webhook-dispatcher/releases/download/v0.2.0/webhook-dispatcher_v0.2.0_linux_arm64.tar.gz"
      sha256 "788919f5f73ac1dd950ea115ec3687c60f0a1b5703e69eb7d64d3018a1fc0514"
      def install
        bin.install "webhook-dispatcher"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/webhook-dispatcher
    EOS
  end

  test do
    system "#{bin}/webhook-dispatcher version"
  end
end
