# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class WebhookDispatcher < Formula
  desc "webhook-dispatcher"
  homepage "https://github.com/sikalabs/webhook-dispatcher"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sikalabs/webhook-dispatcher/releases/download/v0.1.1/webhook-dispatcher_v0.1.1_darwin_amd64.tar.gz"
      sha256 "0ea1cda7795a2ddeaf39719e398f6b853042967072b030103ac9820c1deec932"

      def install
        bin.install "webhook-dispatcher"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sikalabs/webhook-dispatcher/releases/download/v0.1.1/webhook-dispatcher_v0.1.1_darwin_arm64.tar.gz"
      sha256 "8578c2f6545421f269becff04086f49ec08200430b24d49c07e4e8dd367820ea"

      def install
        bin.install "webhook-dispatcher"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/webhook-dispatcher/releases/download/v0.1.1/webhook-dispatcher_v0.1.1_linux_amd64.tar.gz"
      sha256 "a844535b7f286e99699538dcb0ae52d1c6dc61558966884fe290ea150117d836"
      def install
        bin.install "webhook-dispatcher"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sikalabs/webhook-dispatcher/releases/download/v0.1.1/webhook-dispatcher_v0.1.1_linux_arm64.tar.gz"
      sha256 "08aeff11ae899df04494d61af68fe6a766a4bd741c65ff2a2db7817a6f4f1471"
      def install
        bin.install "webhook-dispatcher"
      end
    end
  end

  def caveats
    <<~EOS
      How to use this binary: https://github.com/sikalabs/webhook-dispatcher
    EOS
  end

  test do
    system "#{bin}/webhook-dispatcher version"
  end
end
